nvuillam/npm-groovy-lint

- .groovylintrc.json
- CHANGELOG.md
- lib/example/.groovylintrc.json
- package-lock.json
- package.json
- src/codenarc-caller.js
- src/codenarc-factory.js
- src/config.js
- src/groovy-lint.js
- src/options.js
- test/lint-api.test.js
- test/lint-fix.test.js
- test/lint-format.test.js
- test/miscellaneous.test.js
- Return rules descriptions in results
- New option nolintafter: do not lint again a format or a fix, as the client prefers to request it
- Fixes
- [Issue #13](https://github.com/nvuillam/npm-groovy-lint/issues/13): False positive error ClassNameSameAsFileName
- Sometimes returning wrong .groovylint.json config file
> Return rules descriptions + fixes

- .groovylintrc-recommended-jenkinsfile.json
- CHANGELOG.md
- README.md
- lib/example/.groovylintrc-custom-jenkinsfile.json
- lib/example/.groovylintrc-custom.json
- script-patch-jdeploy-before.js
- src/codenarc-caller.js
- src/codenarc-factory.js
- src/config.js
- src/groovy-lint.js
- src/rules/ElseBlockBraces.js
- src/rules/IfStatementBraces.js
- src/utils.js
- test/lint-fix.rules.test.js
- test/miscellaneous.test.js
- Configuration updates ([#29](https://github.com/nvuillam/npm-groovy-lint/issues/29)):
- New default config "recommended-jenkinsfile". Use it with argument `--config recommended-jenkinsfile`
- Allow to directly target a config file name. Use it with argument `--config /my/custom/path/.groovylintrc-custom-name.json`
- Allow to send a string key that will be used to find config file `--config custom-name`
- Updated fix rules:
- IfStatementBraces
- ElseStatementBraces
> Configuration enhancements + Updated fix rules

- CHANGELOG.md
- lib/example/.groovylintrc-custom.json
- src/config.js
- src/options.js
- test/lint-fix.test.js
- test/lint-format.test.js
- test/miscellaneous.test.js
Take in account user overridden indentation space (and other rules) when using --format option ([#31](https://github.com/nvuillam/npm-groovy-lint/issues/31))
>  Take in account user overridden indentation space

- CHANGELOG.md
- src/codenarc-factory.js
- test/lint-build.test.js
- Fixes
- ignorepattern option not working [#34](https://github.com/nvuillam/npm-groovy-lint/issues/34)
> Take correctly in account --ignorepattern option

- CHANGELOG.md
- README.md
- src/codenarc-caller.js
- src/codenarc-factory.js
- src/groovy-lint-fix.js
- src/groovy-lint.js
- src/options.js
- src/output.js
- test/lint-api.test.js
- test/lint-build.test.js
- Send rule configuration to fix functions
- Add `.gradle` files in default linted files
- Fixes:
- Missing number of linted files returned in summary
- Try to call CodeNarcJava in case there is an error with CodeNarcServer call
> Rule config to fix function, .gradle , callCodeNarcJava fix

- CHANGELOG.md
- README.md
- lib/codenarc-factory.js
- lib/groovy-lint-fix.js
- lib/groovy-lint.js
- lib/rules/BlankLineBeforePackage.js
- lib/rules/DuplicateImport.js
- lib/rules/FileEndsWithoutNewline.js
- lib/rules/UnusedImport.js
- lib/test/helpers/common.js
- lib/test/lint-fix.rules.test.js
- lib/test/lint-format.test.js
- lib/utils.js
- Use os.EOL [(#65)](https://github.com/nvuillam/npm-groovy-lint/pull/65) solving  [(#63)](https://github.com/nvuillam/npm-groovy-lint/issues/63) --fix for indentation adds CRLF line-endings to all files it touches
Closes #63
> Use os.EOL

- CHANGELOG.md
- README.md
- lib/codenarc-caller.js
- lib/config.js
- lib/example/.groovylintrc-codenarc-rulesets.json
- lib/test/miscellaneous.test.js
- Allow to link to [CodeNarc RuleSet files](https://codenarc.github.io/CodeNarc/codenarc-creating-ruleset.html) from `.groovylintrc.json`, using property `"codenarcRulesets"`. Warning: doing so means that all other properties of config file will be ignored.
Closes #82
> codenarcRulesets in .groovylintrc.json config file

- Dockerfile
Update openjdk in dockerfile. This will make container run faster (skip upgrade). 
- Currnelty  each docker run upgrade openjdk before run npm-groovy-lint. This
> Update openjdk in Dockerfile

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Upgrade [java-caller](https://github.com/nvuillam/node-java-caller) to v2.2.3
- Fix Java 8 detection ([#101](https://github.com/nvuillam/npm-groovy-lint/issues/101))
Closes #101
> Fix Java 8 detection

- CHANGELOG.md
- README.md
- lib/.groovylintrc-recommended-jenkinsfile.json
- lib/.groovylintrc-recommended.json
- Disable TrailingComma rule by default until crash is solved in [CodeNarc](https://codenarc.github.io/) ([#75@vscode-groovy-lint](https://github.com/nvuillam/vscode-groovy-lint/issues/75))
> Disable TrailingComma rule by default

- CHANGELOG.md
- lib/.groovylintrc-recommended-jenkinsfile.json
Fixes #144, fixes #141, fixes #142, and fixes #143.
> Exclude UnnecessaryGetter, FactoryMethodName, MethodReturnTypeRequired, and GStringExpressionWithinString in recommended-jenkinsfile

- .pre-commit-hooks.yaml
[pre-commit](https://pre-commit.com) is a powerful tool to enforce code quality and consistency.  I recently  needed to perform groovy linting and discovered this project.  Instead of just forking, I'd like to contribute by enabling people to opt into using this project as a pre-commit hook.  This PR enables that thought the addition of the file `.pre-commit-hooks.yaml` that defines three hooks:
* `npm-groovy-lint`
* calls `npm-groovy-lint`
* `format-npm-groovy-lint`
* calls `npm-groovy-lint --format`
* `fix-npm-groovy-lint`
* calls `npm-groovy-lint --fix` 
This allows users to add to their project's `.pre-commit-config.yaml` (provided the revision gets a patch version bump):
```yaml
---
repos:
- repo: https://github.com/nvuillam/npm-groovy-lint
rev: v8.2.1
hooks:
- id: npm-groovy-lint …
```
> Enable pre-commit hooks to be used by other projects

- README.md
The container created by Docker is not required after usage so adding `--rm` flag will remove it after linter completes.
> Improve Docker snippet to remove created container

- CHANGELOG.md
- README.md
- lib/codenarc-factory.js
- lib/groovy-lint.js
- lib/output.js
- test/miscellaneous.test.js
- Allow to send groovy sources as input from stdin
- If `--format` or `--fix` option is used when source is sent as stdin, the result is output as stdout
Example: `cat path/to/my/Jenkinsfile | npm-groovy-lint --format -`
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/231
> StdIn / StdOut management

- lib/config.js
Solves the following error when using a YAML config file:
```
Parse options error: Cannot read config file: /app/.groovylintrc.yaml
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
```
> Switch from the removed yaml.safeLoad to yaml.load

- lib/groovy-lint-fix.js
Fix the status bar message reporting the variable instead of a filename before it receives the first update.
> fix: status bar message

- lib/rules/UnnecessaryGString.js
- lib/utils.js
Fix the processing of UnnecessaryGString fixes when the string in question includes one or more backslashes.
This is caused by CodeNarc/CodeNarc#749 which results in the output not escaping backslashes in the message we use to determine the value of the string.
This will need to be reverted when we update to a fixed CodeNar version.
Fixes #299
> fix: UnnecessaryGString for strings with slashes

- Dockerfile
```
Java jre or jdk 17 is required
```
-
-
Bump the openjdk to version 17
-
-
> Fix: bump openjdk version from 11 to 17

- lib/groovy-lint.js
- [this commit](https://github.com/nvuillam/npm-groovy-lint/pull/313/commits/e8e6f88fc18792d450f42709a6e35969b95583e9) changed the way results are outputted in`txt` mode. Now, `txt`output contains raw json results which in my opinion clutters the results readability. I believe original intent is for debugging purposes but in that case it should be activated through option like `--verbose`
```
[...]
187   info     The String 'removes' can be wrapped in single quotes instead of double quotes  UnnecessaryGString
193   info     File sshDeploy.groovy does not end with a newline  FileEndsWithoutNewline
npm-groovy-lint results in 35 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │ …
```
> revert txt output results

- docs/CHANGELOG.md
- lib/groovy-lint.js
Issue #338 
Remove the console.log statement. There is already a debug statement with the same information.
> Issue #338: Removing problematic console.log.

- CHANGELOG.md
- docs/CHANGELOG.md
- lib/analytics.js
Wrap analytics so failure to send doesn't trigger a failure.
Fixes: https://github.com/nvuillam/vscode-groovy-lint/issues/173
> fix: analytics send failure error

- CHANGELOG.md
- docs/CHANGELOG.md
- lib/filter.js
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/359
> Fix `console.warning is not a function`

- CHANGELOG.md
- docs/CHANGELOG.md
- package-lock.json
- package.json
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/419
> Upgrade node-java-caller to fix bug with npm-groovy-lint --version on linux

- lib/utils.js
- test/lint-format.test.js
- #468 
Let me know if you want me to make changes
> Fix curly bracket should not get commented out by method comments betweenparenthesis and curly brackets
