nvuillam/npm-groovy-lint

- .gitattributes
- add gitattributes to normalized line-endings
> add gitattributes to normalized line-endings

- .circleci/config.yml
- check-version.js
- package-lock.json
- package.json
- src/index.js
Error message in case of node < 12
> Error message in case of node < 12

- CHANGELOG.md
- README.md
- src/groovy-lint-rules.js
- src/rules/ElseBlockBraces.js
- src/rules/MisorderedStaticImports.js
- src/rules/SpaceBeforeClosingBrace.js
- src/rules/UnnecessaryDefInMethodDeclaration.js
- src/rules/UnnecessaryPackageReference.js
- src/rules/UnnecessaryParenthesesForMethodCallWithClosure.js
- src/utils.js
- New fix rules
- SpaceBeforeClosingBrace
- UnnecessaryDefInMethodDeclaration
- UnnecessaryPackageReference
- UnnecessaryParenthesesForMethodCallWithClosure
- Updated fix rules
- MisorderedStaticImports: Fix `@Grapes` killer fixing rule
- ElseBlockBrace :issue when instruction is on the same line than `else`
> New rules + updated rules

- CHANGELOG.md
- src/analytics.js
- src/codenarc-caller.js
- src/codenarc-factory.js
- src/config.js
- src/groovy-lint.js
- src/index.js
- src/output.js
- test/errors.test.js
- Add CI , rule overrides and crashes in anonymous insights for debugging investigation
- When used as a module, **never crash intentionally with throw**, so when called by module, check linter.status and linter.error instead of try/catch
- 0: ok
- 1: expected error
- 2: unexpected error
- 9: if cancelled request
> Insights + error management update

- CHANGELOG.md
- package-lock.json
- package.json
- src/analytics.js
- src/codenarc-caller.js
- Detect when crash is related to "node" or "java" command not found and return a human readable error message
> Improve error messages

- CHANGELOG.md
- src/codenarc-caller.js
- test/errors.test.js
- Improve performances and avoid `Unknown command: node` error by using childProcess.fork to call CodeNarcServer
> Improve performance + fix issue when node not found

- CHANGELOG.md
- README.md
- lib/codenarc-factory.js
- lib/groovy-lint-rules.js
- lib/java-caller.js
- lib/rules/BlankLineBeforePackage.js
- lib/rules/BracesForIfElse.js
- lib/rules/BracesForMethod.js
- lib/rules/BracesForTryCatchFinally.js
- lib/rules/ClassEndsWithBlankLine.js
- lib/rules/ClassStartsWithBlankLine.js
- lib/rules/MissingBlankLineAfterImports.js
- lib/rules/MissingBlankLineAfterPackage.js
- lib/rules/UnnecessaryGroovyImport.js
- lib/rules/UnusedImport.js
- lib/utils.js
- Avoid to apply wrong fix in case of CodeNarc false positive
- New fix rules
- BlankLineBeforePackage
- Updated fix rules
- BracesForIfElse
- BracesForMethod
- BracesForTryCatchFinally
- ClassEndsWithBlankLine
- ClassStartsWithBlankLine
- MissingBlankLineAfterImports
- MissingBlankLineAfterPackage
- UnnecessaryGroovyImport
- UnusedImport
> New rules and rule fixes

- CHANGELOG.md
- README.md
- lib/rules/Indentation.js
- lib/rules/IndentationClosingBraces.js
- lib/utils.js
- Updated fix rules
- Indentation
- IndentationClosingBrace
> Updated Indentation fix rules

- .circleci/config.yml
- CHANGELOG.md
- README.md
- lib/codenarc-caller.js
- lib/java-caller.js
- lib/test/helpers/init.js
- Install Java 8 using node-jre in case java version found is higher than Java 11 (CodeNarc compatibility is Java 8 to 11)
- add CircleCI test on Java 14 Docker image
> Java >11 compatibility

- README.md
- Readme links to non-existent files
- Fix links in Readme
> Fix references to reference files

- CHANGELOG.md
- README.md
- lib/rules/SpaceAroundOperator.js
- lib/utils.js
- Fixes
- [(#64)](https://github.com/nvuillam/vscode-groovy-lint/issues/64) The contents of a string gets formatted unexpectedly
> Fix SpaceAroundOperator rule

- CHANGELOG.md
- README.md
- lib/analytics.js
- lib/groovy-lint.js
- lib/output.js
> Fix & enhance anonymous statistics

- CHANGELOG.md
- README.md
- lib/codenarc-caller.js
- lib/output.js
- lib/test/miscellaneous.test.js
- Java 14 compatibility (Closes [#77](https://github.com/nvuillam/npm-groovy-lint/issues/7))
> Support Java 14

- CHANGELOG.md
- README.md
- lib/rules/SpaceAfterComma.js
- lib/test/lint-format.test.js
- lib/test/miscellaneous.test.js
- lib/utils.js
- SpaceAfterComma auto-fix rule
> Fix SpaceAfterComma auto-fix rule

- CHANGELOG.md
- README.md
- lib/codenarc-caller.js
- lib/test/miscellaneous.test.js
- package-lock.json
- package.json
- Upgrade [java-caller](https://www.npmjs.com/package/java-caller) to v2.0.0
> Upgrade java-caller

- CHANGELOG.md
- README.md
- lib/groovy-lint.js
- lib/output.js
- lib/test/errors.test.js
- lib/test/helpers/init.js
- lib/test/lint-api.test.js
- lib/utils.js
- Fix [(#90)](https://github.com/nvuillam/npm-groovy-lint/issues/90) When log level is specified number of linted files appear to be off
> --loglevel and --failon option values consistency

- .circleci/config.yml
- CHANGELOG.md
- README.md
- lib/test/miscellaneous.test.js
- package-lock.json
- package.json
> Fix run on Windows when paths containing spaces + add tests on Windows in CI jobs

- .github/workflows/linter.yml
- CHANGELOG.md
- Dockerfile
> Add GitHub Action GitHub Super-Linter to the repository + Dockerfile

- .github/workflows/linter.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> Update Super-Linter GitHub Action config since path filters are now available

- README.md
- internal broken link for Docker usage
- n/a
> Fix internal link

- CHANGELOG.md
- lib/codenarc-factory.js
- lib/index.js
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/232
> Fix error when files sent as positional arguments

- CHANGELOG.md
- lib/codenarc-factory.js
- package-lock.json
- package.json
- test/lint-api.test.js
- Fix error when absolute files sent as positional arguments on a linux system ([#232](https://github.com/nvuillam/npm-groovy-lint/issues/232))
> Fix error when absolute files sent as positional arguments on a linux system

- CHANGELOG.md
- lib/groovy-lint.js
- test/lint-api.test.js
- test/lint-build.test.js
- Do not output results summary in console logs when output is json or sarif
- Add test methods for SARIF called by CLI
> Test methods for single files

- script-deploy-in-vscode.js
Improve the Visual Studio Code deployment script to only copy the files that are contained in a release.
> feat: improve the vscode deployment

- lib/groovy-lint-fix.js
Added some additional debugging the processing of rules to make it easier to understand what's happening when debugging issues.
> chore: improve flow debugging

- .github/workflows/mega-linter.yml
- CHANGELOG.md
- docs/CHANGELOG.md
- lib/groovy-lint.js
- package-lock.json
- package.json
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/296
> Upgrade dependencies + Output codenarc version error

- CHANGELOG.md
- docs/CHANGELOG.md
- lib/groovy-lint.js
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/351
> Fix "directories aren't cleaned up"

- .github/workflows/test.yml
- CHANGELOG.md
- docs/CHANGELOG.md
- package-lock.json
- package.json
Related to https://github.com/nvuillam/vscode-groovy-lint/issues/217#issuecomment-2099808904
> Upgrade java-caller to v4

- README.md
- docs/index.md
- mkdocs.yml
Related to https://github.com/nvuillam/npm-groovy-lint/issues/374
> Add troubleshooting section in documentation

- lib/rules/UnnecessaryGString.js
> Fix #436 autofix of unnecessary g string leaves invalid code in data provider of spock tests
